title: HYMET
description: A hybrid metagenomic tool for taxonomic classification
theme: just-the-docs

url: https://inesbmartins02.github.io/hymet-docs
baseurl: "/hymet-docs" # muito importante!

# Navegação
nav_sort: case_insensitive

# Mostrar link para editar no GitHub (opcional)
repository_url: https://github.com/inesbmartins02/hymet-docs
aux_links:
  View on GitHub: https://github.com/inesbmartins02/hymet-docs

# Ativar busca (opcional mas útil)
search_enabled: true

plugins:
  - jekyll-mermaid